AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lifthus serverless microservices

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        GOOGLE_CLIENT_ID: !Sub "{{resolve:ssm:GOOGLE_CLIENT_ID:1}}"
        HUS_AUTH_DB_NAME: !Sub "{{resolve:ssm:HUS_AUTH_DB_NAME:1}}"
        HUS_AUTH_DB_PASSWORD: !Sub "{{resolve:ssm:HUS_AUTH_DB_PASSWORD:1}}"
        HUS_AUTH_DB_USER: !Sub "{{resolve:ssm:HUS_AUTH_DB_USER:1}}"
        HUS_DB_HOST: !Sub "{{resolve:ssm:HUS_DB_HOST:1}}"
        HUS_DB_PORT: !Sub "{{resolve:ssm:HUS_DB_PORT:1}}"
        HUS_SECRET_KEY: !Sub "{{resolve:ssm:HUS_SECRET_KEY:1}}"
        GOENV: production # --env-vars takes precedence over this in sam local
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"
      AllowMethods: "'*'"
      MaxAge: 43200 # preflight cache
      #AllowCredentials: true # with wildcard origin, this is not allowed actually.
    TracingEnabled: true

Resources:
  # auth services ==================================================
  LifthusAuthApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: LifthusAuthApi
      StageName: prod
      Domain:
        DomainName: "auth.lifthus.com"
        CertificateArn: !Sub "{{resolve:ssm:CLOUDHUS_ACM_ARN:1}}"
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Sub "{{resolve:ssm:LIFTHUS_HOSTED_ZONE_ID:1}}}"
          RecordName: "auth.lifthus.com"
  LifthusAuthService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/lifthus-auth/
      Handler: lifthus-auth
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        LifthusAuthServiceRoot:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: LifthusAuthApi
            Path: "/auth"
            Method: ANY
        LifthusAuthServiceProxy:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: LifthusAuthApi
            Path: /auth/{proxy+} # auth service uses subdomain, but to do proxy locally, prefix is needed.
            Method: ANY

  # lifthus api ==================================================
  LifthusApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: LifthusApi
      StageName: prod
      Domain:
        DomainName: "api.lifthus.com"
        CertificateArn: !Sub "{{resolve:ssm:CLOUDHUS_ACM_ARN:1}}"
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Sub "{{resolve:ssm:LIFTHUS_HOSTED_ZONE_ID:1}}}"
          RecordName: "api.lifthus.com"
  # lifthus post service
  LifthusPostService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/lifthus-post/dist
      Handler: main.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        LifthusPostServiceRoot:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: LifthusApi
            Path: "/post"
            Method: ANY
        LifthusPostServiceProxy:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: LifthusApi
            Path: /post/{proxy+} # auth service uses subdomain, but to do proxy locally, prefix is needed.
            Method: ANY

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
          - ""
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
          - ""
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      AutoConfigurationEnabled: "true"
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
