// Code generated by ent, DO NOT EDIT.

package programrelease

import (
	"routine/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldLTE(FieldID, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEQ(FieldText, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldLTE(FieldCreatedAt, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.ProgramRelease {
	return predicate.ProgramRelease(sql.FieldContainsFold(FieldText, v))
}

// HasProgram applies the HasEdge predicate on the "program" edge.
func HasProgram() predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProgramTable, ProgramColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProgramWith applies the HasEdge predicate on the "program" edge with a given conditions (other predicates).
func HasProgramWith(preds ...predicate.Program) predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		step := newProgramStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasS3ProgramImages applies the HasEdge predicate on the "s3_program_images" edge.
func HasS3ProgramImages() predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, S3ProgramImagesTable, S3ProgramImagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasS3ProgramImagesWith applies the HasEdge predicate on the "s3_program_images" edge with a given conditions (other predicates).
func HasS3ProgramImagesWith(preds ...predicate.S3ProgramImage) predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		step := newS3ProgramImagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoutines applies the HasEdge predicate on the "routines" edge.
func HasRoutines() predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RoutinesTable, RoutinesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoutinesWith applies the HasEdge predicate on the "routines" edge with a given conditions (other predicates).
func HasRoutinesWith(preds ...predicate.Routine) predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		step := newRoutinesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProgramRelease) predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProgramRelease) predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProgramRelease) predicate.ProgramRelease {
	return predicate.ProgramRelease(func(s *sql.Selector) {
		p(s.Not())
	})
}
