// Code generated by ent, DO NOT EDIT.

package actimage

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the actimage type in the database.
	Label = "act_image"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActVersionCode holds the string denoting the act_version_code field in the database.
	FieldActVersionCode = "act_version_code"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// FieldSrc holds the string denoting the src field in the database.
	FieldSrc = "src"
	// EdgeActVersion holds the string denoting the act_version edge name in mutations.
	EdgeActVersion = "act_version"
	// Table holds the table name of the actimage in the database.
	Table = "act_images"
	// ActVersionTable is the table that holds the act_version relation/edge.
	ActVersionTable = "act_images"
	// ActVersionInverseTable is the table name for the ActVersion entity.
	// It exists in this package in order to avoid circular dependency with the "actversion" package.
	ActVersionInverseTable = "act_versions"
	// ActVersionColumn is the table column denoting the act_version relation/edge.
	ActVersionColumn = "act_version_act_images"
)

// Columns holds all SQL columns for actimage fields.
var Columns = []string{
	FieldID,
	FieldActVersionCode,
	FieldOrder,
	FieldSrc,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "act_images"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"act_version_act_images",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ActVersionCodeValidator is a validator for the "act_version_code" field. It is called by the builders before save.
	ActVersionCodeValidator func(string) error
	// SrcValidator is a validator for the "src" field. It is called by the builders before save.
	SrcValidator func(string) error
)

// OrderOption defines the ordering options for the ActImage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActVersionCode orders the results by the act_version_code field.
func ByActVersionCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActVersionCode, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// BySrc orders the results by the src field.
func BySrc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSrc, opts...).ToFunc()
}

// ByActVersionField orders the results by act_version field.
func ByActVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActVersionStep(), sql.OrderByField(field, opts...))
	}
}
func newActVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActVersionTable, ActVersionColumn),
	)
}
