// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"routine/internal/ent/dayroutine"
	"routine/internal/ent/routineact"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DayRoutineCreate is the builder for creating a DayRoutine entity.
type DayRoutineCreate struct {
	config
	mutation *DayRoutineMutation
	hooks    []Hook
}

// SetDay sets the "day" field.
func (drc *DayRoutineCreate) SetDay(i int) *DayRoutineCreate {
	drc.mutation.SetDay(i)
	return drc
}

// SetID sets the "id" field.
func (drc *DayRoutineCreate) SetID(i int64) *DayRoutineCreate {
	drc.mutation.SetID(i)
	return drc
}

// AddRoutineActIDs adds the "routine_acts" edge to the RoutineAct entity by IDs.
func (drc *DayRoutineCreate) AddRoutineActIDs(ids ...int64) *DayRoutineCreate {
	drc.mutation.AddRoutineActIDs(ids...)
	return drc
}

// AddRoutineActs adds the "routine_acts" edges to the RoutineAct entity.
func (drc *DayRoutineCreate) AddRoutineActs(r ...*RoutineAct) *DayRoutineCreate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return drc.AddRoutineActIDs(ids...)
}

// Mutation returns the DayRoutineMutation object of the builder.
func (drc *DayRoutineCreate) Mutation() *DayRoutineMutation {
	return drc.mutation
}

// Save creates the DayRoutine in the database.
func (drc *DayRoutineCreate) Save(ctx context.Context) (*DayRoutine, error) {
	return withHooks(ctx, drc.sqlSave, drc.mutation, drc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (drc *DayRoutineCreate) SaveX(ctx context.Context) *DayRoutine {
	v, err := drc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (drc *DayRoutineCreate) Exec(ctx context.Context) error {
	_, err := drc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (drc *DayRoutineCreate) ExecX(ctx context.Context) {
	if err := drc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (drc *DayRoutineCreate) check() error {
	if _, ok := drc.mutation.Day(); !ok {
		return &ValidationError{Name: "day", err: errors.New(`ent: missing required field "DayRoutine.day"`)}
	}
	return nil
}

func (drc *DayRoutineCreate) sqlSave(ctx context.Context) (*DayRoutine, error) {
	if err := drc.check(); err != nil {
		return nil, err
	}
	_node, _spec := drc.createSpec()
	if err := sqlgraph.CreateNode(ctx, drc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	drc.mutation.id = &_node.ID
	drc.mutation.done = true
	return _node, nil
}

func (drc *DayRoutineCreate) createSpec() (*DayRoutine, *sqlgraph.CreateSpec) {
	var (
		_node = &DayRoutine{config: drc.config}
		_spec = sqlgraph.NewCreateSpec(dayroutine.Table, sqlgraph.NewFieldSpec(dayroutine.FieldID, field.TypeInt64))
	)
	if id, ok := drc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := drc.mutation.Day(); ok {
		_spec.SetField(dayroutine.FieldDay, field.TypeInt, value)
		_node.Day = value
	}
	if nodes := drc.mutation.RoutineActsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dayroutine.RoutineActsTable,
			Columns: []string{dayroutine.RoutineActsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routineact.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DayRoutineCreateBulk is the builder for creating many DayRoutine entities in bulk.
type DayRoutineCreateBulk struct {
	config
	builders []*DayRoutineCreate
}

// Save creates the DayRoutine entities in the database.
func (drcb *DayRoutineCreateBulk) Save(ctx context.Context) ([]*DayRoutine, error) {
	specs := make([]*sqlgraph.CreateSpec, len(drcb.builders))
	nodes := make([]*DayRoutine, len(drcb.builders))
	mutators := make([]Mutator, len(drcb.builders))
	for i := range drcb.builders {
		func(i int, root context.Context) {
			builder := drcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DayRoutineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, drcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, drcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, drcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (drcb *DayRoutineCreateBulk) SaveX(ctx context.Context) []*DayRoutine {
	v, err := drcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (drcb *DayRoutineCreateBulk) Exec(ctx context.Context) error {
	_, err := drcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (drcb *DayRoutineCreateBulk) ExecX(ctx context.Context) {
	if err := drcb.Exec(ctx); err != nil {
		panic(err)
	}
}
