// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"routine/internal/ent/act"
	"routine/internal/ent/predicate"
	"routine/internal/ent/s3actimage"
	"routine/internal/ent/s3image"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// S3ActImageUpdate is the builder for updating S3ActImage entities.
type S3ActImageUpdate struct {
	config
	hooks    []Hook
	mutation *S3ActImageMutation
}

// Where appends a list predicates to the S3ActImageUpdate builder.
func (siu *S3ActImageUpdate) Where(ps ...predicate.S3ActImage) *S3ActImageUpdate {
	siu.mutation.Where(ps...)
	return siu
}

// SetOrder sets the "order" field.
func (siu *S3ActImageUpdate) SetOrder(i int) *S3ActImageUpdate {
	siu.mutation.ResetOrder()
	siu.mutation.SetOrder(i)
	return siu
}

// AddOrder adds i to the "order" field.
func (siu *S3ActImageUpdate) AddOrder(i int) *S3ActImageUpdate {
	siu.mutation.AddOrder(i)
	return siu
}

// SetActID sets the "act_id" field.
func (siu *S3ActImageUpdate) SetActID(i int64) *S3ActImageUpdate {
	siu.mutation.SetActID(i)
	return siu
}

// SetImageID sets the "image_id" field.
func (siu *S3ActImageUpdate) SetImageID(i int64) *S3ActImageUpdate {
	siu.mutation.SetImageID(i)
	return siu
}

// SetAct sets the "act" edge to the Act entity.
func (siu *S3ActImageUpdate) SetAct(a *Act) *S3ActImageUpdate {
	return siu.SetActID(a.ID)
}

// SetS3ImageID sets the "s3_image" edge to the S3Image entity by ID.
func (siu *S3ActImageUpdate) SetS3ImageID(id int64) *S3ActImageUpdate {
	siu.mutation.SetS3ImageID(id)
	return siu
}

// SetS3Image sets the "s3_image" edge to the S3Image entity.
func (siu *S3ActImageUpdate) SetS3Image(s *S3Image) *S3ActImageUpdate {
	return siu.SetS3ImageID(s.ID)
}

// Mutation returns the S3ActImageMutation object of the builder.
func (siu *S3ActImageUpdate) Mutation() *S3ActImageMutation {
	return siu.mutation
}

// ClearAct clears the "act" edge to the Act entity.
func (siu *S3ActImageUpdate) ClearAct() *S3ActImageUpdate {
	siu.mutation.ClearAct()
	return siu
}

// ClearS3Image clears the "s3_image" edge to the S3Image entity.
func (siu *S3ActImageUpdate) ClearS3Image() *S3ActImageUpdate {
	siu.mutation.ClearS3Image()
	return siu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (siu *S3ActImageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, siu.sqlSave, siu.mutation, siu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (siu *S3ActImageUpdate) SaveX(ctx context.Context) int {
	affected, err := siu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (siu *S3ActImageUpdate) Exec(ctx context.Context) error {
	_, err := siu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (siu *S3ActImageUpdate) ExecX(ctx context.Context) {
	if err := siu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (siu *S3ActImageUpdate) check() error {
	if _, ok := siu.mutation.ActID(); siu.mutation.ActCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "S3ActImage.act"`)
	}
	if _, ok := siu.mutation.S3ImageID(); siu.mutation.S3ImageCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "S3ActImage.s3_image"`)
	}
	return nil
}

func (siu *S3ActImageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := siu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3actimage.Table, s3actimage.Columns, sqlgraph.NewFieldSpec(s3actimage.FieldID, field.TypeInt64))
	if ps := siu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := siu.mutation.Order(); ok {
		_spec.SetField(s3actimage.FieldOrder, field.TypeInt, value)
	}
	if value, ok := siu.mutation.AddedOrder(); ok {
		_spec.AddField(s3actimage.FieldOrder, field.TypeInt, value)
	}
	if siu.mutation.ActCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   s3actimage.ActTable,
			Columns: []string{s3actimage.ActColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(act.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := siu.mutation.ActIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   s3actimage.ActTable,
			Columns: []string{s3actimage.ActColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(act.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if siu.mutation.S3ImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   s3actimage.S3ImageTable,
			Columns: []string{s3actimage.S3ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(s3image.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := siu.mutation.S3ImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   s3actimage.S3ImageTable,
			Columns: []string{s3actimage.S3ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(s3image.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, siu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3actimage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	siu.mutation.done = true
	return n, nil
}

// S3ActImageUpdateOne is the builder for updating a single S3ActImage entity.
type S3ActImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *S3ActImageMutation
}

// SetOrder sets the "order" field.
func (siuo *S3ActImageUpdateOne) SetOrder(i int) *S3ActImageUpdateOne {
	siuo.mutation.ResetOrder()
	siuo.mutation.SetOrder(i)
	return siuo
}

// AddOrder adds i to the "order" field.
func (siuo *S3ActImageUpdateOne) AddOrder(i int) *S3ActImageUpdateOne {
	siuo.mutation.AddOrder(i)
	return siuo
}

// SetActID sets the "act_id" field.
func (siuo *S3ActImageUpdateOne) SetActID(i int64) *S3ActImageUpdateOne {
	siuo.mutation.SetActID(i)
	return siuo
}

// SetImageID sets the "image_id" field.
func (siuo *S3ActImageUpdateOne) SetImageID(i int64) *S3ActImageUpdateOne {
	siuo.mutation.SetImageID(i)
	return siuo
}

// SetAct sets the "act" edge to the Act entity.
func (siuo *S3ActImageUpdateOne) SetAct(a *Act) *S3ActImageUpdateOne {
	return siuo.SetActID(a.ID)
}

// SetS3ImageID sets the "s3_image" edge to the S3Image entity by ID.
func (siuo *S3ActImageUpdateOne) SetS3ImageID(id int64) *S3ActImageUpdateOne {
	siuo.mutation.SetS3ImageID(id)
	return siuo
}

// SetS3Image sets the "s3_image" edge to the S3Image entity.
func (siuo *S3ActImageUpdateOne) SetS3Image(s *S3Image) *S3ActImageUpdateOne {
	return siuo.SetS3ImageID(s.ID)
}

// Mutation returns the S3ActImageMutation object of the builder.
func (siuo *S3ActImageUpdateOne) Mutation() *S3ActImageMutation {
	return siuo.mutation
}

// ClearAct clears the "act" edge to the Act entity.
func (siuo *S3ActImageUpdateOne) ClearAct() *S3ActImageUpdateOne {
	siuo.mutation.ClearAct()
	return siuo
}

// ClearS3Image clears the "s3_image" edge to the S3Image entity.
func (siuo *S3ActImageUpdateOne) ClearS3Image() *S3ActImageUpdateOne {
	siuo.mutation.ClearS3Image()
	return siuo
}

// Where appends a list predicates to the S3ActImageUpdate builder.
func (siuo *S3ActImageUpdateOne) Where(ps ...predicate.S3ActImage) *S3ActImageUpdateOne {
	siuo.mutation.Where(ps...)
	return siuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (siuo *S3ActImageUpdateOne) Select(field string, fields ...string) *S3ActImageUpdateOne {
	siuo.fields = append([]string{field}, fields...)
	return siuo
}

// Save executes the query and returns the updated S3ActImage entity.
func (siuo *S3ActImageUpdateOne) Save(ctx context.Context) (*S3ActImage, error) {
	return withHooks(ctx, siuo.sqlSave, siuo.mutation, siuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (siuo *S3ActImageUpdateOne) SaveX(ctx context.Context) *S3ActImage {
	node, err := siuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (siuo *S3ActImageUpdateOne) Exec(ctx context.Context) error {
	_, err := siuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (siuo *S3ActImageUpdateOne) ExecX(ctx context.Context) {
	if err := siuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (siuo *S3ActImageUpdateOne) check() error {
	if _, ok := siuo.mutation.ActID(); siuo.mutation.ActCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "S3ActImage.act"`)
	}
	if _, ok := siuo.mutation.S3ImageID(); siuo.mutation.S3ImageCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "S3ActImage.s3_image"`)
	}
	return nil
}

func (siuo *S3ActImageUpdateOne) sqlSave(ctx context.Context) (_node *S3ActImage, err error) {
	if err := siuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3actimage.Table, s3actimage.Columns, sqlgraph.NewFieldSpec(s3actimage.FieldID, field.TypeInt64))
	id, ok := siuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "S3ActImage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := siuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, s3actimage.FieldID)
		for _, f := range fields {
			if !s3actimage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != s3actimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := siuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := siuo.mutation.Order(); ok {
		_spec.SetField(s3actimage.FieldOrder, field.TypeInt, value)
	}
	if value, ok := siuo.mutation.AddedOrder(); ok {
		_spec.AddField(s3actimage.FieldOrder, field.TypeInt, value)
	}
	if siuo.mutation.ActCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   s3actimage.ActTable,
			Columns: []string{s3actimage.ActColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(act.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := siuo.mutation.ActIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   s3actimage.ActTable,
			Columns: []string{s3actimage.ActColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(act.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if siuo.mutation.S3ImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   s3actimage.S3ImageTable,
			Columns: []string{s3actimage.S3ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(s3image.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := siuo.mutation.S3ImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   s3actimage.S3ImageTable,
			Columns: []string{s3actimage.S3ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(s3image.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &S3ActImage{config: siuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, siuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3actimage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	siuo.mutation.done = true
	return _node, nil
}
