// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Act is the predicate function for act builders.
type Act func(*sql.Selector)

// Program is the predicate function for program builders.
type Program func(*sql.Selector)
