basePath: /routine
host: localhost:9100
info:
  contact:
    email: lifthus531@gmail.com
    name: API Support
    url: lifthus531@gmail.com
  description: This is Project-Hus's subservice Lifthus's routine management server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Lifthus routine server
  version: 0.0.0
paths:
  /act:
    post:
      parameters:
      - description: author of act
        in: formData
        name: author
        required: true
        type: string
      - description: name of act
        in: formData
        name: name
        required: true
        type: string
      - description: type of act
        in: formData
        name: actType
        required: true
        type: string
      - description: text of act
        in: formData
        name: text
        required: true
        type: string
      - description: images of act
        in: formData
        name: images
        type: file
      - description: lifthus_st
        in: header
        name: Authorization
        required: true
        type: string
      responses: {}
      tags:
      - ""
  /act/{code}:
    get:
      parameters:
      - description: act code
        in: path
        name: code
        required: true
        type: string
      responses:
        "200":
          description: returns act info as json
        "400":
          description: invalid request
        "404":
          description: act not found
        "500":
          description: internal server error
      summary: get act by code
      tags:
      - act
swagger: "2.0"
