basePath: /routine
definitions:
  dto.CreateActRequestDto:
    properties:
      actType:
        type: string
      author:
        type: string
      imageSrcs:
        items:
          type: string
        type: array
      name:
        type: string
      text:
        type: string
    type: object
host: localhost:9100
info:
  contact:
    email: lifthus531@gmail.com
    name: API Support
    url: lifthus531@gmail.com
  description: This is Project-Hus's subservice Lifthus's routine management server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Lifthus routine server
  version: 0.0.0
paths:
  /act:
    post:
      parameters:
      - description: lifthus_st
        in: header
        name: Authorization
        required: true
        type: string
      - description: create act dto
        in: body
        name: creatActDto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateActRequestDto'
      responses: {}
      tags:
      - ""
  /act/{code}:
    get:
      parameters:
      - description: act code
        in: path
        name: code
        required: true
        type: string
      responses:
        "200":
          description: returns act info as json
        "400":
          description: invalid request
        "404":
          description: act not found
        "500":
          description: internal server error
      summary: get act by code
      tags:
      - act
  /act/upgarde:
    post:
      parameters:
      - description: author of act
        in: formData
        name: author
        required: true
        type: string
      responses: {}
      tags:
      - ""
  /images/{target}:
    post:
      parameters:
      - description: images for target
        in: path
        name: target
        required: true
        type: string
      - description: images of act
        in: formData
        name: images
        required: true
        type: file
      - description: lifthus_st
        in: header
        name: Authorization
        required: true
        type: string
      responses: {}
      tags:
      - ""
swagger: "2.0"
