basePath: /routine
definitions:
  dto.CreateActRequestDto:
    properties:
      actType:
        type: string
      author:
        type: string
      imageSrcs:
        items:
          type: string
        type: array
      name:
        type: string
      text:
        type: string
    type: object
  dto.CreateProgramRequestDailyRoutineDto:
    properties:
      day:
        type: integer
      routineActs:
        items:
          $ref: '#/definitions/dto.CreateProgramRequestRoutineActDto'
        type: array
    type: object
  dto.CreateProgramRequestDto:
    properties:
      author:
        type: string
      dailyRoutines:
        items:
          $ref: '#/definitions/dto.CreateProgramRequestDailyRoutineDto'
        type: array
      derivedFrom:
        type: string
      imageSrcs:
        items:
          type: string
        type: array
      programType:
        type: string
      text:
        type: string
      title:
        type: string
    type: object
  dto.CreateProgramRequestRoutineActDto:
    properties:
      actVersion:
        type: string
      order:
        type: integer
      ratioOrSecs:
        type: number
      repsOrMeters:
        type: integer
      stage:
        type: string
    type: object
  dto.UpgradeActRequestDto:
    properties:
      actCode:
        type: string
      imageSrcs:
        items:
          type: string
        type: array
      text:
        type: string
    type: object
host: localhost:9100
info:
  contact:
    email: lifthus531@gmail.com
    name: API Support
    url: lifthus531@gmail.com
  description: This is Project-Hus's subservice Lifthus's routine management server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Lifthus routine server
  version: 0.0.0
paths:
  /act:
    get:
      parameters:
      - description: act code
        in: query
        name: code
        type: string
      responses:
        "200":
          description: returns act info as json
        "400":
          description: invalid request
        "404":
          description: act not found
        "500":
          description: internal server error
      summary: get specific act
      tags:
      - act
    post:
      parameters:
      - description: lifthus_st
        in: header
        name: Authorization
        required: true
        type: string
      - description: create act dto
        in: body
        name: creatActDto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateActRequestDto'
      responses: {}
      tags:
      - act
  /act/upgrade:
    post:
      parameters:
      - description: lifthus_st
        in: header
        name: Authorization
        required: true
        type: string
      - description: upgrade act dto
        in: body
        name: upgradeActDto
        required: true
        schema:
          $ref: '#/definitions/dto.UpgradeActRequestDto'
      responses: {}
      tags:
      - act
  /acts:
    get:
      parameters:
      - description: act name
        in: query
        name: name
        type: string
      responses:
        "200":
          description: returns acts info as json array
        "400":
          description: invalid request
        "404":
          description: act not found
        "500":
          description: internal server error
      summary: get acts that match the query
      tags:
      - act
  /images/{target}:
    post:
      parameters:
      - description: images for target
        in: path
        name: target
        required: true
        type: string
      - description: images of act
        in: formData
        name: images
        required: true
        type: file
      - description: lifthus_st
        in: header
        name: Authorization
        required: true
        type: string
      responses: {}
      tags:
      - ""
  /program/{code}:
    get:
      parameters:
      - description: program code
        in: path
        name: code
        required: true
        type: string
      responses: {}
      tags:
      - program
  /program/weekly:
    post:
      parameters:
      - description: lifthus_st
        in: header
        name: Authorization
        required: true
        type: string
      - description: create program dto
        in: body
        name: creatProgramDto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateProgramRequestDto'
      responses: {}
      tags:
      - program
swagger: "2.0"
