// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"routine/ent/act"
	"routine/ent/dailyroutinerec"
	"routine/ent/predicate"
	"routine/ent/routineact"
	"routine/ent/routineactrec"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoutineActRecQuery is the builder for querying RoutineActRec entities.
type RoutineActRecQuery struct {
	config
	ctx                 *QueryContext
	order               []routineactrec.OrderOption
	inters              []Interceptor
	predicates          []predicate.RoutineActRec
	withDailyRoutineRec *DailyRoutineRecQuery
	withAct             *ActQuery
	withRoutineAct      *RoutineActQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoutineActRecQuery builder.
func (rarq *RoutineActRecQuery) Where(ps ...predicate.RoutineActRec) *RoutineActRecQuery {
	rarq.predicates = append(rarq.predicates, ps...)
	return rarq
}

// Limit the number of records to be returned by this query.
func (rarq *RoutineActRecQuery) Limit(limit int) *RoutineActRecQuery {
	rarq.ctx.Limit = &limit
	return rarq
}

// Offset to start from.
func (rarq *RoutineActRecQuery) Offset(offset int) *RoutineActRecQuery {
	rarq.ctx.Offset = &offset
	return rarq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rarq *RoutineActRecQuery) Unique(unique bool) *RoutineActRecQuery {
	rarq.ctx.Unique = &unique
	return rarq
}

// Order specifies how the records should be ordered.
func (rarq *RoutineActRecQuery) Order(o ...routineactrec.OrderOption) *RoutineActRecQuery {
	rarq.order = append(rarq.order, o...)
	return rarq
}

// QueryDailyRoutineRec chains the current query on the "daily_routine_rec" edge.
func (rarq *RoutineActRecQuery) QueryDailyRoutineRec() *DailyRoutineRecQuery {
	query := (&DailyRoutineRecClient{config: rarq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rarq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rarq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(routineactrec.Table, routineactrec.FieldID, selector),
			sqlgraph.To(dailyroutinerec.Table, dailyroutinerec.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, routineactrec.DailyRoutineRecTable, routineactrec.DailyRoutineRecColumn),
		)
		fromU = sqlgraph.SetNeighbors(rarq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAct chains the current query on the "act" edge.
func (rarq *RoutineActRecQuery) QueryAct() *ActQuery {
	query := (&ActClient{config: rarq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rarq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rarq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(routineactrec.Table, routineactrec.FieldID, selector),
			sqlgraph.To(act.Table, act.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, routineactrec.ActTable, routineactrec.ActColumn),
		)
		fromU = sqlgraph.SetNeighbors(rarq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoutineAct chains the current query on the "routine_act" edge.
func (rarq *RoutineActRecQuery) QueryRoutineAct() *RoutineActQuery {
	query := (&RoutineActClient{config: rarq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rarq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rarq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(routineactrec.Table, routineactrec.FieldID, selector),
			sqlgraph.To(routineact.Table, routineact.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, routineactrec.RoutineActTable, routineactrec.RoutineActColumn),
		)
		fromU = sqlgraph.SetNeighbors(rarq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoutineActRec entity from the query.
// Returns a *NotFoundError when no RoutineActRec was found.
func (rarq *RoutineActRecQuery) First(ctx context.Context) (*RoutineActRec, error) {
	nodes, err := rarq.Limit(1).All(setContextOp(ctx, rarq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{routineactrec.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rarq *RoutineActRecQuery) FirstX(ctx context.Context) *RoutineActRec {
	node, err := rarq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoutineActRec ID from the query.
// Returns a *NotFoundError when no RoutineActRec ID was found.
func (rarq *RoutineActRecQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = rarq.Limit(1).IDs(setContextOp(ctx, rarq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{routineactrec.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rarq *RoutineActRecQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := rarq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoutineActRec entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoutineActRec entity is found.
// Returns a *NotFoundError when no RoutineActRec entities are found.
func (rarq *RoutineActRecQuery) Only(ctx context.Context) (*RoutineActRec, error) {
	nodes, err := rarq.Limit(2).All(setContextOp(ctx, rarq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{routineactrec.Label}
	default:
		return nil, &NotSingularError{routineactrec.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rarq *RoutineActRecQuery) OnlyX(ctx context.Context) *RoutineActRec {
	node, err := rarq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoutineActRec ID in the query.
// Returns a *NotSingularError when more than one RoutineActRec ID is found.
// Returns a *NotFoundError when no entities are found.
func (rarq *RoutineActRecQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = rarq.Limit(2).IDs(setContextOp(ctx, rarq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{routineactrec.Label}
	default:
		err = &NotSingularError{routineactrec.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rarq *RoutineActRecQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := rarq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoutineActRecs.
func (rarq *RoutineActRecQuery) All(ctx context.Context) ([]*RoutineActRec, error) {
	ctx = setContextOp(ctx, rarq.ctx, "All")
	if err := rarq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoutineActRec, *RoutineActRecQuery]()
	return withInterceptors[[]*RoutineActRec](ctx, rarq, qr, rarq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rarq *RoutineActRecQuery) AllX(ctx context.Context) []*RoutineActRec {
	nodes, err := rarq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoutineActRec IDs.
func (rarq *RoutineActRecQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if rarq.ctx.Unique == nil && rarq.path != nil {
		rarq.Unique(true)
	}
	ctx = setContextOp(ctx, rarq.ctx, "IDs")
	if err = rarq.Select(routineactrec.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rarq *RoutineActRecQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := rarq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rarq *RoutineActRecQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rarq.ctx, "Count")
	if err := rarq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rarq, querierCount[*RoutineActRecQuery](), rarq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rarq *RoutineActRecQuery) CountX(ctx context.Context) int {
	count, err := rarq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rarq *RoutineActRecQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rarq.ctx, "Exist")
	switch _, err := rarq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rarq *RoutineActRecQuery) ExistX(ctx context.Context) bool {
	exist, err := rarq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoutineActRecQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rarq *RoutineActRecQuery) Clone() *RoutineActRecQuery {
	if rarq == nil {
		return nil
	}
	return &RoutineActRecQuery{
		config:              rarq.config,
		ctx:                 rarq.ctx.Clone(),
		order:               append([]routineactrec.OrderOption{}, rarq.order...),
		inters:              append([]Interceptor{}, rarq.inters...),
		predicates:          append([]predicate.RoutineActRec{}, rarq.predicates...),
		withDailyRoutineRec: rarq.withDailyRoutineRec.Clone(),
		withAct:             rarq.withAct.Clone(),
		withRoutineAct:      rarq.withRoutineAct.Clone(),
		// clone intermediate query.
		sql:  rarq.sql.Clone(),
		path: rarq.path,
	}
}

// WithDailyRoutineRec tells the query-builder to eager-load the nodes that are connected to
// the "daily_routine_rec" edge. The optional arguments are used to configure the query builder of the edge.
func (rarq *RoutineActRecQuery) WithDailyRoutineRec(opts ...func(*DailyRoutineRecQuery)) *RoutineActRecQuery {
	query := (&DailyRoutineRecClient{config: rarq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rarq.withDailyRoutineRec = query
	return rarq
}

// WithAct tells the query-builder to eager-load the nodes that are connected to
// the "act" edge. The optional arguments are used to configure the query builder of the edge.
func (rarq *RoutineActRecQuery) WithAct(opts ...func(*ActQuery)) *RoutineActRecQuery {
	query := (&ActClient{config: rarq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rarq.withAct = query
	return rarq
}

// WithRoutineAct tells the query-builder to eager-load the nodes that are connected to
// the "routine_act" edge. The optional arguments are used to configure the query builder of the edge.
func (rarq *RoutineActRecQuery) WithRoutineAct(opts ...func(*RoutineActQuery)) *RoutineActRecQuery {
	query := (&RoutineActClient{config: rarq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rarq.withRoutineAct = query
	return rarq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Author uint64 `json:"author,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoutineActRec.Query().
//		GroupBy(routineactrec.FieldAuthor).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rarq *RoutineActRecQuery) GroupBy(field string, fields ...string) *RoutineActRecGroupBy {
	rarq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoutineActRecGroupBy{build: rarq}
	grbuild.flds = &rarq.ctx.Fields
	grbuild.label = routineactrec.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Author uint64 `json:"author,omitempty"`
//	}
//
//	client.RoutineActRec.Query().
//		Select(routineactrec.FieldAuthor).
//		Scan(ctx, &v)
func (rarq *RoutineActRecQuery) Select(fields ...string) *RoutineActRecSelect {
	rarq.ctx.Fields = append(rarq.ctx.Fields, fields...)
	sbuild := &RoutineActRecSelect{RoutineActRecQuery: rarq}
	sbuild.label = routineactrec.Label
	sbuild.flds, sbuild.scan = &rarq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoutineActRecSelect configured with the given aggregations.
func (rarq *RoutineActRecQuery) Aggregate(fns ...AggregateFunc) *RoutineActRecSelect {
	return rarq.Select().Aggregate(fns...)
}

func (rarq *RoutineActRecQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rarq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rarq); err != nil {
				return err
			}
		}
	}
	for _, f := range rarq.ctx.Fields {
		if !routineactrec.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rarq.path != nil {
		prev, err := rarq.path(ctx)
		if err != nil {
			return err
		}
		rarq.sql = prev
	}
	return nil
}

func (rarq *RoutineActRecQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoutineActRec, error) {
	var (
		nodes       = []*RoutineActRec{}
		_spec       = rarq.querySpec()
		loadedTypes = [3]bool{
			rarq.withDailyRoutineRec != nil,
			rarq.withAct != nil,
			rarq.withRoutineAct != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoutineActRec).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoutineActRec{config: rarq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rarq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rarq.withDailyRoutineRec; query != nil {
		if err := rarq.loadDailyRoutineRec(ctx, query, nodes, nil,
			func(n *RoutineActRec, e *DailyRoutineRec) { n.Edges.DailyRoutineRec = e }); err != nil {
			return nil, err
		}
	}
	if query := rarq.withAct; query != nil {
		if err := rarq.loadAct(ctx, query, nodes, nil,
			func(n *RoutineActRec, e *Act) { n.Edges.Act = e }); err != nil {
			return nil, err
		}
	}
	if query := rarq.withRoutineAct; query != nil {
		if err := rarq.loadRoutineAct(ctx, query, nodes, nil,
			func(n *RoutineActRec, e *RoutineAct) { n.Edges.RoutineAct = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rarq *RoutineActRecQuery) loadDailyRoutineRec(ctx context.Context, query *DailyRoutineRecQuery, nodes []*RoutineActRec, init func(*RoutineActRec), assign func(*RoutineActRec, *DailyRoutineRec)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*RoutineActRec)
	for i := range nodes {
		fk := nodes[i].DailyRoutineRecID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(dailyroutinerec.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "daily_routine_rec_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rarq *RoutineActRecQuery) loadAct(ctx context.Context, query *ActQuery, nodes []*RoutineActRec, init func(*RoutineActRec), assign func(*RoutineActRec, *Act)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*RoutineActRec)
	for i := range nodes {
		fk := nodes[i].ActID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(act.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "act_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rarq *RoutineActRecQuery) loadRoutineAct(ctx context.Context, query *RoutineActQuery, nodes []*RoutineActRec, init func(*RoutineActRec), assign func(*RoutineActRec, *RoutineAct)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*RoutineActRec)
	for i := range nodes {
		if nodes[i].RoutineActID == nil {
			continue
		}
		fk := *nodes[i].RoutineActID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(routineact.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "routine_act_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rarq *RoutineActRecQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rarq.querySpec()
	_spec.Node.Columns = rarq.ctx.Fields
	if len(rarq.ctx.Fields) > 0 {
		_spec.Unique = rarq.ctx.Unique != nil && *rarq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rarq.driver, _spec)
}

func (rarq *RoutineActRecQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(routineactrec.Table, routineactrec.Columns, sqlgraph.NewFieldSpec(routineactrec.FieldID, field.TypeUint64))
	_spec.From = rarq.sql
	if unique := rarq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rarq.path != nil {
		_spec.Unique = true
	}
	if fields := rarq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routineactrec.FieldID)
		for i := range fields {
			if fields[i] != routineactrec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rarq.withDailyRoutineRec != nil {
			_spec.Node.AddColumnOnce(routineactrec.FieldDailyRoutineRecID)
		}
		if rarq.withAct != nil {
			_spec.Node.AddColumnOnce(routineactrec.FieldActID)
		}
		if rarq.withRoutineAct != nil {
			_spec.Node.AddColumnOnce(routineactrec.FieldRoutineActID)
		}
	}
	if ps := rarq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rarq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rarq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rarq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rarq *RoutineActRecQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rarq.driver.Dialect())
	t1 := builder.Table(routineactrec.Table)
	columns := rarq.ctx.Fields
	if len(columns) == 0 {
		columns = routineactrec.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rarq.sql != nil {
		selector = rarq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rarq.ctx.Unique != nil && *rarq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rarq.predicates {
		p(selector)
	}
	for _, p := range rarq.order {
		p(selector)
	}
	if offset := rarq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rarq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoutineActRecGroupBy is the group-by builder for RoutineActRec entities.
type RoutineActRecGroupBy struct {
	selector
	build *RoutineActRecQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rargb *RoutineActRecGroupBy) Aggregate(fns ...AggregateFunc) *RoutineActRecGroupBy {
	rargb.fns = append(rargb.fns, fns...)
	return rargb
}

// Scan applies the selector query and scans the result into the given value.
func (rargb *RoutineActRecGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rargb.build.ctx, "GroupBy")
	if err := rargb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoutineActRecQuery, *RoutineActRecGroupBy](ctx, rargb.build, rargb, rargb.build.inters, v)
}

func (rargb *RoutineActRecGroupBy) sqlScan(ctx context.Context, root *RoutineActRecQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rargb.fns))
	for _, fn := range rargb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rargb.flds)+len(rargb.fns))
		for _, f := range *rargb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rargb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rargb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoutineActRecSelect is the builder for selecting fields of RoutineActRec entities.
type RoutineActRecSelect struct {
	*RoutineActRecQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rars *RoutineActRecSelect) Aggregate(fns ...AggregateFunc) *RoutineActRecSelect {
	rars.fns = append(rars.fns, fns...)
	return rars
}

// Scan applies the selector query and scans the result into the given value.
func (rars *RoutineActRecSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rars.ctx, "Select")
	if err := rars.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoutineActRecQuery, *RoutineActRecSelect](ctx, rars.RoutineActRecQuery, rars, rars.inters, v)
}

func (rars *RoutineActRecSelect) sqlScan(ctx context.Context, root *RoutineActRecQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rars.fns))
	for _, fn := range rars.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rars.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rars.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
