// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"routine/ent/dailyroutinerec"
	"routine/ent/predicate"
	"routine/ent/programrec"
	"routine/ent/weeklyroutine"
	"routine/ent/weeklyroutinerec"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WeeklyRoutineRecQuery is the builder for querying WeeklyRoutineRec entities.
type WeeklyRoutineRecQuery struct {
	config
	ctx                  *QueryContext
	order                []weeklyroutinerec.OrderOption
	inters               []Interceptor
	predicates           []predicate.WeeklyRoutineRec
	withWeeklyRoutine    *WeeklyRoutineQuery
	withProgramRec       *ProgramRecQuery
	withDailyRoutineRecs *DailyRoutineRecQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WeeklyRoutineRecQuery builder.
func (wrrq *WeeklyRoutineRecQuery) Where(ps ...predicate.WeeklyRoutineRec) *WeeklyRoutineRecQuery {
	wrrq.predicates = append(wrrq.predicates, ps...)
	return wrrq
}

// Limit the number of records to be returned by this query.
func (wrrq *WeeklyRoutineRecQuery) Limit(limit int) *WeeklyRoutineRecQuery {
	wrrq.ctx.Limit = &limit
	return wrrq
}

// Offset to start from.
func (wrrq *WeeklyRoutineRecQuery) Offset(offset int) *WeeklyRoutineRecQuery {
	wrrq.ctx.Offset = &offset
	return wrrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wrrq *WeeklyRoutineRecQuery) Unique(unique bool) *WeeklyRoutineRecQuery {
	wrrq.ctx.Unique = &unique
	return wrrq
}

// Order specifies how the records should be ordered.
func (wrrq *WeeklyRoutineRecQuery) Order(o ...weeklyroutinerec.OrderOption) *WeeklyRoutineRecQuery {
	wrrq.order = append(wrrq.order, o...)
	return wrrq
}

// QueryWeeklyRoutine chains the current query on the "weekly_routine" edge.
func (wrrq *WeeklyRoutineRecQuery) QueryWeeklyRoutine() *WeeklyRoutineQuery {
	query := (&WeeklyRoutineClient{config: wrrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wrrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wrrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(weeklyroutinerec.Table, weeklyroutinerec.FieldID, selector),
			sqlgraph.To(weeklyroutine.Table, weeklyroutine.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, weeklyroutinerec.WeeklyRoutineTable, weeklyroutinerec.WeeklyRoutineColumn),
		)
		fromU = sqlgraph.SetNeighbors(wrrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProgramRec chains the current query on the "program_rec" edge.
func (wrrq *WeeklyRoutineRecQuery) QueryProgramRec() *ProgramRecQuery {
	query := (&ProgramRecClient{config: wrrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wrrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wrrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(weeklyroutinerec.Table, weeklyroutinerec.FieldID, selector),
			sqlgraph.To(programrec.Table, programrec.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, weeklyroutinerec.ProgramRecTable, weeklyroutinerec.ProgramRecColumn),
		)
		fromU = sqlgraph.SetNeighbors(wrrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDailyRoutineRecs chains the current query on the "daily_routine_recs" edge.
func (wrrq *WeeklyRoutineRecQuery) QueryDailyRoutineRecs() *DailyRoutineRecQuery {
	query := (&DailyRoutineRecClient{config: wrrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wrrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wrrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(weeklyroutinerec.Table, weeklyroutinerec.FieldID, selector),
			sqlgraph.To(dailyroutinerec.Table, dailyroutinerec.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, weeklyroutinerec.DailyRoutineRecsTable, weeklyroutinerec.DailyRoutineRecsColumn),
		)
		fromU = sqlgraph.SetNeighbors(wrrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WeeklyRoutineRec entity from the query.
// Returns a *NotFoundError when no WeeklyRoutineRec was found.
func (wrrq *WeeklyRoutineRecQuery) First(ctx context.Context) (*WeeklyRoutineRec, error) {
	nodes, err := wrrq.Limit(1).All(setContextOp(ctx, wrrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{weeklyroutinerec.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wrrq *WeeklyRoutineRecQuery) FirstX(ctx context.Context) *WeeklyRoutineRec {
	node, err := wrrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WeeklyRoutineRec ID from the query.
// Returns a *NotFoundError when no WeeklyRoutineRec ID was found.
func (wrrq *WeeklyRoutineRecQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = wrrq.Limit(1).IDs(setContextOp(ctx, wrrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{weeklyroutinerec.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wrrq *WeeklyRoutineRecQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := wrrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WeeklyRoutineRec entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WeeklyRoutineRec entity is found.
// Returns a *NotFoundError when no WeeklyRoutineRec entities are found.
func (wrrq *WeeklyRoutineRecQuery) Only(ctx context.Context) (*WeeklyRoutineRec, error) {
	nodes, err := wrrq.Limit(2).All(setContextOp(ctx, wrrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{weeklyroutinerec.Label}
	default:
		return nil, &NotSingularError{weeklyroutinerec.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wrrq *WeeklyRoutineRecQuery) OnlyX(ctx context.Context) *WeeklyRoutineRec {
	node, err := wrrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WeeklyRoutineRec ID in the query.
// Returns a *NotSingularError when more than one WeeklyRoutineRec ID is found.
// Returns a *NotFoundError when no entities are found.
func (wrrq *WeeklyRoutineRecQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = wrrq.Limit(2).IDs(setContextOp(ctx, wrrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{weeklyroutinerec.Label}
	default:
		err = &NotSingularError{weeklyroutinerec.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wrrq *WeeklyRoutineRecQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := wrrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WeeklyRoutineRecs.
func (wrrq *WeeklyRoutineRecQuery) All(ctx context.Context) ([]*WeeklyRoutineRec, error) {
	ctx = setContextOp(ctx, wrrq.ctx, "All")
	if err := wrrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WeeklyRoutineRec, *WeeklyRoutineRecQuery]()
	return withInterceptors[[]*WeeklyRoutineRec](ctx, wrrq, qr, wrrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wrrq *WeeklyRoutineRecQuery) AllX(ctx context.Context) []*WeeklyRoutineRec {
	nodes, err := wrrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WeeklyRoutineRec IDs.
func (wrrq *WeeklyRoutineRecQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if wrrq.ctx.Unique == nil && wrrq.path != nil {
		wrrq.Unique(true)
	}
	ctx = setContextOp(ctx, wrrq.ctx, "IDs")
	if err = wrrq.Select(weeklyroutinerec.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wrrq *WeeklyRoutineRecQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := wrrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wrrq *WeeklyRoutineRecQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wrrq.ctx, "Count")
	if err := wrrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wrrq, querierCount[*WeeklyRoutineRecQuery](), wrrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wrrq *WeeklyRoutineRecQuery) CountX(ctx context.Context) int {
	count, err := wrrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wrrq *WeeklyRoutineRecQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wrrq.ctx, "Exist")
	switch _, err := wrrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wrrq *WeeklyRoutineRecQuery) ExistX(ctx context.Context) bool {
	exist, err := wrrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WeeklyRoutineRecQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wrrq *WeeklyRoutineRecQuery) Clone() *WeeklyRoutineRecQuery {
	if wrrq == nil {
		return nil
	}
	return &WeeklyRoutineRecQuery{
		config:               wrrq.config,
		ctx:                  wrrq.ctx.Clone(),
		order:                append([]weeklyroutinerec.OrderOption{}, wrrq.order...),
		inters:               append([]Interceptor{}, wrrq.inters...),
		predicates:           append([]predicate.WeeklyRoutineRec{}, wrrq.predicates...),
		withWeeklyRoutine:    wrrq.withWeeklyRoutine.Clone(),
		withProgramRec:       wrrq.withProgramRec.Clone(),
		withDailyRoutineRecs: wrrq.withDailyRoutineRecs.Clone(),
		// clone intermediate query.
		sql:  wrrq.sql.Clone(),
		path: wrrq.path,
	}
}

// WithWeeklyRoutine tells the query-builder to eager-load the nodes that are connected to
// the "weekly_routine" edge. The optional arguments are used to configure the query builder of the edge.
func (wrrq *WeeklyRoutineRecQuery) WithWeeklyRoutine(opts ...func(*WeeklyRoutineQuery)) *WeeklyRoutineRecQuery {
	query := (&WeeklyRoutineClient{config: wrrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wrrq.withWeeklyRoutine = query
	return wrrq
}

// WithProgramRec tells the query-builder to eager-load the nodes that are connected to
// the "program_rec" edge. The optional arguments are used to configure the query builder of the edge.
func (wrrq *WeeklyRoutineRecQuery) WithProgramRec(opts ...func(*ProgramRecQuery)) *WeeklyRoutineRecQuery {
	query := (&ProgramRecClient{config: wrrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wrrq.withProgramRec = query
	return wrrq
}

// WithDailyRoutineRecs tells the query-builder to eager-load the nodes that are connected to
// the "daily_routine_recs" edge. The optional arguments are used to configure the query builder of the edge.
func (wrrq *WeeklyRoutineRecQuery) WithDailyRoutineRecs(opts ...func(*DailyRoutineRecQuery)) *WeeklyRoutineRecQuery {
	query := (&DailyRoutineRecClient{config: wrrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wrrq.withDailyRoutineRecs = query
	return wrrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProgramRecID uint64 `json:"program_rec_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WeeklyRoutineRec.Query().
//		GroupBy(weeklyroutinerec.FieldProgramRecID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wrrq *WeeklyRoutineRecQuery) GroupBy(field string, fields ...string) *WeeklyRoutineRecGroupBy {
	wrrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WeeklyRoutineRecGroupBy{build: wrrq}
	grbuild.flds = &wrrq.ctx.Fields
	grbuild.label = weeklyroutinerec.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProgramRecID uint64 `json:"program_rec_id,omitempty"`
//	}
//
//	client.WeeklyRoutineRec.Query().
//		Select(weeklyroutinerec.FieldProgramRecID).
//		Scan(ctx, &v)
func (wrrq *WeeklyRoutineRecQuery) Select(fields ...string) *WeeklyRoutineRecSelect {
	wrrq.ctx.Fields = append(wrrq.ctx.Fields, fields...)
	sbuild := &WeeklyRoutineRecSelect{WeeklyRoutineRecQuery: wrrq}
	sbuild.label = weeklyroutinerec.Label
	sbuild.flds, sbuild.scan = &wrrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WeeklyRoutineRecSelect configured with the given aggregations.
func (wrrq *WeeklyRoutineRecQuery) Aggregate(fns ...AggregateFunc) *WeeklyRoutineRecSelect {
	return wrrq.Select().Aggregate(fns...)
}

func (wrrq *WeeklyRoutineRecQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wrrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wrrq); err != nil {
				return err
			}
		}
	}
	for _, f := range wrrq.ctx.Fields {
		if !weeklyroutinerec.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wrrq.path != nil {
		prev, err := wrrq.path(ctx)
		if err != nil {
			return err
		}
		wrrq.sql = prev
	}
	return nil
}

func (wrrq *WeeklyRoutineRecQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WeeklyRoutineRec, error) {
	var (
		nodes       = []*WeeklyRoutineRec{}
		_spec       = wrrq.querySpec()
		loadedTypes = [3]bool{
			wrrq.withWeeklyRoutine != nil,
			wrrq.withProgramRec != nil,
			wrrq.withDailyRoutineRecs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WeeklyRoutineRec).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WeeklyRoutineRec{config: wrrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wrrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wrrq.withWeeklyRoutine; query != nil {
		if err := wrrq.loadWeeklyRoutine(ctx, query, nodes, nil,
			func(n *WeeklyRoutineRec, e *WeeklyRoutine) { n.Edges.WeeklyRoutine = e }); err != nil {
			return nil, err
		}
	}
	if query := wrrq.withProgramRec; query != nil {
		if err := wrrq.loadProgramRec(ctx, query, nodes, nil,
			func(n *WeeklyRoutineRec, e *ProgramRec) { n.Edges.ProgramRec = e }); err != nil {
			return nil, err
		}
	}
	if query := wrrq.withDailyRoutineRecs; query != nil {
		if err := wrrq.loadDailyRoutineRecs(ctx, query, nodes,
			func(n *WeeklyRoutineRec) { n.Edges.DailyRoutineRecs = []*DailyRoutineRec{} },
			func(n *WeeklyRoutineRec, e *DailyRoutineRec) {
				n.Edges.DailyRoutineRecs = append(n.Edges.DailyRoutineRecs, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wrrq *WeeklyRoutineRecQuery) loadWeeklyRoutine(ctx context.Context, query *WeeklyRoutineQuery, nodes []*WeeklyRoutineRec, init func(*WeeklyRoutineRec), assign func(*WeeklyRoutineRec, *WeeklyRoutine)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*WeeklyRoutineRec)
	for i := range nodes {
		fk := nodes[i].WeeklyRoutineID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(weeklyroutine.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "weekly_routine_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (wrrq *WeeklyRoutineRecQuery) loadProgramRec(ctx context.Context, query *ProgramRecQuery, nodes []*WeeklyRoutineRec, init func(*WeeklyRoutineRec), assign func(*WeeklyRoutineRec, *ProgramRec)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*WeeklyRoutineRec)
	for i := range nodes {
		fk := nodes[i].ProgramRecID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(programrec.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "program_rec_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (wrrq *WeeklyRoutineRecQuery) loadDailyRoutineRecs(ctx context.Context, query *DailyRoutineRecQuery, nodes []*WeeklyRoutineRec, init func(*WeeklyRoutineRec), assign func(*WeeklyRoutineRec, *DailyRoutineRec)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*WeeklyRoutineRec)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(dailyroutinerec.FieldWeeklyRoutineRecID)
	}
	query.Where(predicate.DailyRoutineRec(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(weeklyroutinerec.DailyRoutineRecsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WeeklyRoutineRecID
		if fk == nil {
			return fmt.Errorf(`foreign-key "weekly_routine_rec_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "weekly_routine_rec_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (wrrq *WeeklyRoutineRecQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wrrq.querySpec()
	_spec.Node.Columns = wrrq.ctx.Fields
	if len(wrrq.ctx.Fields) > 0 {
		_spec.Unique = wrrq.ctx.Unique != nil && *wrrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wrrq.driver, _spec)
}

func (wrrq *WeeklyRoutineRecQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(weeklyroutinerec.Table, weeklyroutinerec.Columns, sqlgraph.NewFieldSpec(weeklyroutinerec.FieldID, field.TypeUint64))
	_spec.From = wrrq.sql
	if unique := wrrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wrrq.path != nil {
		_spec.Unique = true
	}
	if fields := wrrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, weeklyroutinerec.FieldID)
		for i := range fields {
			if fields[i] != weeklyroutinerec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if wrrq.withWeeklyRoutine != nil {
			_spec.Node.AddColumnOnce(weeklyroutinerec.FieldWeeklyRoutineID)
		}
		if wrrq.withProgramRec != nil {
			_spec.Node.AddColumnOnce(weeklyroutinerec.FieldProgramRecID)
		}
	}
	if ps := wrrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wrrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wrrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wrrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wrrq *WeeklyRoutineRecQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wrrq.driver.Dialect())
	t1 := builder.Table(weeklyroutinerec.Table)
	columns := wrrq.ctx.Fields
	if len(columns) == 0 {
		columns = weeklyroutinerec.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wrrq.sql != nil {
		selector = wrrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wrrq.ctx.Unique != nil && *wrrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wrrq.predicates {
		p(selector)
	}
	for _, p := range wrrq.order {
		p(selector)
	}
	if offset := wrrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wrrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WeeklyRoutineRecGroupBy is the group-by builder for WeeklyRoutineRec entities.
type WeeklyRoutineRecGroupBy struct {
	selector
	build *WeeklyRoutineRecQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wrrgb *WeeklyRoutineRecGroupBy) Aggregate(fns ...AggregateFunc) *WeeklyRoutineRecGroupBy {
	wrrgb.fns = append(wrrgb.fns, fns...)
	return wrrgb
}

// Scan applies the selector query and scans the result into the given value.
func (wrrgb *WeeklyRoutineRecGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wrrgb.build.ctx, "GroupBy")
	if err := wrrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WeeklyRoutineRecQuery, *WeeklyRoutineRecGroupBy](ctx, wrrgb.build, wrrgb, wrrgb.build.inters, v)
}

func (wrrgb *WeeklyRoutineRecGroupBy) sqlScan(ctx context.Context, root *WeeklyRoutineRecQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wrrgb.fns))
	for _, fn := range wrrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wrrgb.flds)+len(wrrgb.fns))
		for _, f := range *wrrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wrrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wrrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WeeklyRoutineRecSelect is the builder for selecting fields of WeeklyRoutineRec entities.
type WeeklyRoutineRecSelect struct {
	*WeeklyRoutineRecQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wrrs *WeeklyRoutineRecSelect) Aggregate(fns ...AggregateFunc) *WeeklyRoutineRecSelect {
	wrrs.fns = append(wrrs.fns, fns...)
	return wrrs
}

// Scan applies the selector query and scans the result into the given value.
func (wrrs *WeeklyRoutineRecSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wrrs.ctx, "Select")
	if err := wrrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WeeklyRoutineRecQuery, *WeeklyRoutineRecSelect](ctx, wrrs.WeeklyRoutineRecQuery, wrrs, wrrs.inters, v)
}

func (wrrs *WeeklyRoutineRecSelect) sqlScan(ctx context.Context, root *WeeklyRoutineRecQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wrrs.fns))
	for _, fn := range wrrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wrrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wrrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
