package domain

const (
	CODE_LENGTH = 8

	PROGRAM_TITLE_MAX_LENGTH  = 50
	PROGRAM_IMAGES_MAX_NUMBER = 1
	PROGRAM_TEXT_MAX_LENGTH   = 5000

	PROGRAM_VERSION_DESCRIPTION_MAX_LENGTH = 1000

	ACT_NAME_MAX_LENGTH   = 50
	ACT_IMAGES_MAX_NUMBER = 1
	ACT_TEXT_MAX_LENGTH   = 1000
)
