package domain

const (
	CODE_LENGTH = 8

	PROGRAM_TITLE_MIN_LENGTH  = 5
	PROGRAM_TITLE_MAX_LENGTH  = 50
	PROGRAM_IMAGES_MIN_NUMBER = 0
	PROGRAM_IMAGES_MAX_NUMBER = 1
	PROGRAM_TEXT_MIN_LENGTH   = 50
	PROGRAM_TEXT_MAX_LENGTH   = 5000

	ACT_NAME_MIN_LENGTH   = 3
	ACT_NAME_MAX_LENGTH   = 50
	ACT_IMAGES_MIN_NUMBER = 0
	ACT_IMAGES_MAX_NUMBER = 1
	ACT_TEXT_MIN_LENGTH   = 10
	ACT_TEXT_MAX_LENGTH   = 1000
)
